name: 'Setup Project'
description: 'Common setup steps for all deployment jobs'
inputs:
  tag-name:
    description: 'Tag name for versioning'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun pm version ${{ inputs.tag-name }} --no-git-tag-version
    - run: bun run tauri icon static/favicon-32x32.png
